---
title: "Research Environment"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

The lab is situated in the UCL Department of Language and Cognition, in London's Bloomsbury neighbourhood, close to King's Cross and Russell Square stations. The Language and Cognition department has an international reputation for research excellence in the development of spoken and written language, the cognitive bases of language in adults, the inter-relationship of language with other cognitive systems, and impairments of language and communication across the lifespan. We are part of the broader Division of Psychology and Language Sciences (PALS), which includes a wide range of research departments such as UCL Institute of Cognitive Neuroscience, Experimental Psychology, Speech, Hearing and Phonetic Sciences (SHaPS) and Clinical, Educational and Health Psychology. Beyond PALS, UCL also has a Centre for Research in Autism and Education (CRAE) as part of IOE, UCL's Faculty of Education and Society.

Postdoctoral researchers in the ISLaND lab at UCL can enjoy access to numerous research seminars and interest groups across the division, forge collaborations within and outside the department, and gain experience in BSc/MSc student supervision.
